// Prints the Homebrew formula for a release from dist-bin/checksums.txt. Usage: node scripts/formula.mjs <version>
import { readFileSync } from "node:fs";
const version = (process.argv[2] ?? "").replace(/^v/, "");
if (!version) throw new Error("usage: formula.mjs <version>");
const sums = Object.fromEntries(
  readFileSync(new URL("../dist-bin/checksums.txt", import.meta.url), "utf8").trim().split("\n").map((l) => l.split(/\s+/).reverse()),
);
const asset = (name) => {
  const file = `pingpigeon-${name}.tar.gz`;
  if (!sums[file]) throw new Error(`no checksum for ${file}`);
  return `      url "https://github.com/chiefsmurph/pingpigeon-cli/releases/download/v${version}/${file}"\n      sha256 "${sums[file]}"`;
};
process.stdout.write(`# Generated by pingpigeon-cli's release workflow (scripts/formula.mjs). Do not edit by hand.
class Pingpigeon < Formula
  desc "Email, push and text yourself from the terminal"
  homepage "https://pingpigeon.app"
  version "${version}"
  license "MIT"

  on_macos do
    on_arm do
${asset("darwin-arm64")}
    end
    on_intel do
${asset("darwin-x64")}
    end
  end

  on_linux do
    on_arm do
${asset("linux-arm64")}
    end
    on_intel do
${asset("linux-x64")}
    end
  end

  def install
    bin.install "pingpigeon"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/pingpigeon --version")
  end
end
`);
