// Bakes the version into src/generated.ts so it is compiled in: a standalone binary has no package.json to read.
import { readFileSync, writeFileSync } from "node:fs";
const root = new URL("..", import.meta.url);
const pkg = JSON.parse(readFileSync(new URL("package.json", root), "utf8"));
writeFileSync(
  new URL("src/generated.ts", root),
  `// Generated by scripts/gen.mjs from package.json (run on every build). Do not edit.\nexport const VERSION = ${JSON.stringify(pkg.version)};\n`,
);
